spring.application.name=e-comProj

# PostgreSQL (commented out - enable when DB is ready)
spring.datasource.url= jdbc:postgresql://localhost:5432/ecomerce
spring.datasource.username=postgres
spring.datasource.password=Krishn@2775

frontend.url = http://localhost:5173/

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

